### ISSUE TITLE
连接rollsite错误：ROLLSITE_GRPC_ERROR(137, "Connect this rollsite error!") when adding an exchange

### ISSUE THREAD

**Issue by EvoEcho** [FederatedAI/FATE-Cloud#112]
版本 1.4

使用KubeFate以docker-compose方式配置好FATE，并分别部署Fate-manager, cloud-manager, 按照使用手册运行，在添加Exchange时出现 “连接此Rollsite错误！" 报错。

FATE可成功运行双边测试，以及执行其他任务。

logs:  /data/projects/cloud-manager/logs/2021-09-21/info.2021-09-21.log in cloud-manager

```
2021-09-21 13:22:00 [34mINFO [0;39m [pool-2-thread-1] (FederatedModelService.java:158) - start detective
2021-09-21 13:23:14 [34mINFO [0;39m [http-nio-9999-exec-8] (FederatedExchangeController.java:50) - url:find paged exchange, requestBody:ExchangeQueryQo(networkAccess=47.100.xx.xx:9370)
2021-09-21 13:23:14 [34mINFO [0;39m [http-nio-9999-exec-8] (FederatedExchangeService.java:250) - query request to exchange, ip:47.100.xx.xx,port:9370, key:exchange, partyId:admin, operator:get_route_table
2021-09-21 13:24:00 [34mINFO [0;39m [pool-2-thread-1] (FederatedModelService.java:158) - start detective
```
logs: /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.log in rollsite

```
[INFO ][54572][2021-09-21 13:23:14,502][grpc-server-9370-0,pid:7,tid:17][audit:87] - dst={partyId=admin}|operator=get_route_table
[ERROR][54696][2021-09-21 13:23:14,626][grpc-server-9370-0,pid:7,tid:17][c.w.e.r.EggSiteServicer:144] - [UNARYCALL][SERVER] onError. rsKey=__rsk#######, metadata={"dst":{"name":"","partyId":"admin","role":""},"operator":"get_route_table","seq":"0","ack":"0","ext":"","version":""}
io.grpc.StatusRuntimeException: UNKNOWN: UNKNOWN: 
[Roll Site Error TransInfo] 
 location msg=JSONObject["ip"] not found. 
 stack info=org.json.JSONException: JSONObject["ip"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at com.webank.eggroll.rollsite.Router$.query(Router.scala:79)
	at com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:80)
	at com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 

exception trans path: rollsite(exchange) --> rollsite(9998)
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.27.2.jar:1.27.2]
	at com.webank.eggroll.rollsite.TransferExceptionUtils$.throwableToException(TransferExceptionUtils.scala:43) ~[eggroll-roll-site-2.2.1.jar:?]
	at com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:152) [eggroll-roll-site-2.2.1.jar:?]
	at com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406) [eggroll-core-2.2.1.jar:?]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [grpc-stub-1.27.2.jar:1.27.2]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.27.2.jar:1.27.2]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.27.2.jar:1.27.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) [grpc-api-1.27.2.jar:1.27.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) [grpc-api-1.27.2.jar:1.27.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817) [grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.27.2.jar:1.27.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by EvoEcho** [comment]
如图，填写网关信息后点击按钮，或自行填写路由信息提交，都会报错。

![image](https://user-images.githubusercontent.com/38654848/134182073-4b22adef-0794-49f2-b39a-fc6e8bcdb168.png)

**Comment by zhihuiwan** [comment]
请确保cloud-manager的配置文件config/application.properties中的配置与
exchange下的rolliste的conf/eggroll.properties配置文件配置配置项保持一致.

# 配置项
rollsite 的 eggroll.rollsite.party.id= 需对应 cloud-manager 的 exchange.partyId=
rollsite 的 eggroll.rollsite.route.table.key= 需对应 cloud-manager 的 exchange.key=

# 并配置cloud-manager服务的ip地址到rollsite白名单列表, eg:127.0.0.1,127.0.0.1
rollsite 的 eggroll.rollsite.route.table.whitelist=
