### ISSUE TITLE
The routing table not have current party=exchange and default party

### ISSUE THREAD

**Issue by amenhub** [FederatedAI/FATE-Cloud#127]
hi bro, when I added the exchange route, the log information prompted me to encounter the following problems.

[ERROR][13327122][2022-02-14 13:54:38,802][grpc-server-9370-12,pid:28998,tid:41][c.w.e.r.EggSiteServicer:144] - [UNARYCALL][SERVER] onError. rsKey=__rsk#######, metadata={"dst":{"name":"","partyId":"exchange","role":""},"operator":"get_route_table","seq":"0","ack":"0","ext":"","version":""}
io.grpc.StatusRuntimeException: UNKNOWN: 
[Roll Site Error TransInfo] 
 location msg=The routing table not have current party=exchange and default party 
 stack info=java.lang.Exception: The routing table not have current party=exchange and default party
        at com.webank.eggroll.rollsite.Router$.query(Router.scala:41)
        at com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:80)
        at com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
 

exception trans path: 192.168.0.3(exchange)
        at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.27.2.jar:1.27.2]
        at com.webank.eggroll.rollsite.TransferExceptionUtils$.throwableToException(TransferExceptionUtils.scala:43) ~[eggroll-roll-site-2.4.2.jar:?]
        at com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:154) [eggroll-roll-site-2.4.2.jar:?]
        at com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406) [eggroll-core-2.2.2.jar:?]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [grpc-stub-1.27.2.jar:1.27.2]
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.27.2.jar:1.27.2]
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.27.2.jar:1.27.2]
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) [grpc-api-1.27.2.jar:1.27.2]
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) [grpc-api-1.27.2.jar:1.27.2]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [grpc-core-1.27.2.jar:1.27.2]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817) [grpc-core-1.27.2.jar:1.27.2]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.27.2.jar:1.27.2]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.27.2.jar:1.27.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.Exception: The routing table not have current party=exchange and default party
        at com.webank.eggroll.rollsite.Router$.query(Router.scala:41) ~[eggroll-roll-site-2.4.2.jar:?]
        at com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:80) [eggroll-roll-site-2.4.2.jar:?]
        ... 13 more

please how can i solve it, thanks!

**Comment by pizhicheng** [comment]
Can you paste the configuration of route_table in exchange. This file is in dir eggroll/conf.
Here is a example:
{
    "route_table":{
        "admin":{
            "default":[
                {
                    "ip":"192.168.0.0.1",
                    "port":9370
                }
            ]
        }
    },
    "permission":{
        "default_allow":true
    }
}

**Comment by amenhub** [comment]
ofcourse!
**eggroll.properties:**
[eggroll]
# for roll site. rename in the next round
eggroll.rollsite.coordinator=fate
eggroll.rollsite.host=192.168.0.3
eggroll.rollsite.port=9370
eggroll.rollsite.party.id=exchange
eggroll.rollsite.route.table.path=conf/route_table.json
eggroll.rollsite.route.table.key=exchange
eggroll.rollsite.route.table.whitelist=192.168.0.3
eggroll.rollsite.jvm.options=-XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:logs/eggroll/rollsite.gc.log
eggroll.rollsite.push.max.retry=3
eggroll.rollsite.push.long.retry=2
eggroll.rollsite.push.batches.per.stream=10
eggroll.rollsite.adapter.sendbuf.size=100000
eggroll.core.grpc.channel.keepalive.timeout.sec=20

**route_table:**
{
  "route_table":
  {
    "9999":
    {
      "default":[
        {
          "port": 9370,
          "ip": "192.168.0.2"
        }
      ]
    },
    "10000":
    {
      "default":[
        {
          "port": 9370,
          "ip": "192.168.0.1"
        }
      ]
    }
  },
  "permission":
  {
    "default_allow": true
  }
}

**Comment by pizhicheng** [comment]
You should add a route in route table, which partyId is exchange. this party id name is decided by the configuration of eggroll.rollsite.party.id.

PS: The application.properties in cloud-manager also need to match with this configuration.

**Comment by amenhub** [comment]
> You should add a route in route table, which partyId is exchange. this party id name is decided by the configuration of eggroll.rollsite.party.id.
> 
> PS: The application.properties in cloud-manager also need to match with this configuration.

**Comment by amenhub** [comment]
> You should add a route in route table, which partyId is exchange. this party id name is decided by the configuration of eggroll.rollsite.party.id.
> 
> PS: The application.properties in cloud-manager also need to match with this configuration. properties in cloud-manager **exchange.partyId=** must equals to properties **eggroll.rollsite.party.id=** properties in cloud-manager **exchange.key=** must equals to properties **eggroll.rollsite.route.table.key=**

I know, but this part of the description does not say that it is necessary to add the route information with the party id as exchange. 
https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_eggroll/fate-exchange_deployment_guide.zh.md#543-eggroll%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BF%AE%E6%94%B9

So, I just need to add an exchange, ok?

**Comment by pizhicheng** [comment]
> > You should add a route in route table, which partyId is exchange. this party id name is decided by the configuration of eggroll.rollsite.party.id.
> > PS: The application.properties in cloud-manager also need to match with this configuration. properties in cloud-manager **exchange.partyId=** must equals to properties **eggroll.rollsite.party.id=** properties in cloud-manager **exchange.key=** must equals to properties **eggroll.rollsite.route.table.key=**
> 
> I know, but this part of the description does not say that it is necessary to add the route information with the party id as exchange. https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_eggroll/fate-exchange_deployment_guide.zh.md#543-eggroll%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BF%AE%E6%94%B9
> 
> So, I just need to add an exchange, ok?

Yes

**Comment by amenhub** [comment]
> > > You should add a route in route table, which partyId is exchange. this party id name is decided by the configuration of eggroll.rollsite.party.id.
> > > PS: The application.properties in cloud-manager also need to match with this configuration. properties in cloud-manager **exchange.partyId=** must equals to properties **eggroll.rollsite.party.id=** properties in cloud-manager **exchange.key=** must equals to properties **eggroll.rollsite.route.table.key=**
> > 
> > 
> > I know, but this part of the description does not say that it is necessary to add the route information with the party id as exchange. https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_eggroll/fate-exchange_deployment_guide.zh.md#543-eggroll%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BF%AE%E6%94%B9
> > So, I just need to add an exchange, ok?
> 
> Yes

thanks! 

In addition, I would like to ask a question, whether the exchange gateway entry in this picture, as well as the ip and port of the rollsite entry and exit are all configured correctly, as well as the routing information below.
![image](https://user-images.githubusercontent.com/35909818/154010077-d88f50e6-8262-44eb-b296-fac4532e3dd9.png)

**Comment by pizhicheng** [comment]
> > > > You should add a route in route table, which partyId is exchange. this party id name is decided by the configuration of eggroll.rollsite.party.id.
> > > > PS: The application.properties in cloud-manager also need to match with this configuration. properties in cloud-manager **exchange.partyId=** must equals to properties **eggroll.rollsite.party.id=** properties in cloud-manager **exchange.key=** must equals to properties **eggroll.rollsite.route.table.key=**
> > > 
> > > 
> > > I know, but this part of the description does not say that it is necessary to add the route information with the party id as exchange. https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_eggroll/fate-exchange_deployment_guide.zh.md#543-eggroll%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BF%AE%E6%94%B9
> > > So, I just need to add an exchange, ok?
> > 
> > 
> > Yes
> 
> thanks!
> 
> In addition, I would like to ask a question, whether the exchange gateway entry in this picture, as well as the ip and port of the rollsite entry and exit are all configured correctly, as well as the routing information below. ![image](https://user-images.githubusercontent.com/35909818/154010077-d88f50e6-8262-44eb-b296-fac4532e3dd9.png)

It seems to be ok

**Comment by pizhicheng** [comment]
> > > > You should add a route in route table, which partyId is exchange. this party id name is decided by the configuration of eggroll.rollsite.party.id.
> > > > PS: The application.properties in cloud-manager also need to match with this configuration. properties in cloud-manager **exchange.partyId=** must equals to properties **eggroll.rollsite.party.id=** properties in cloud-manager **exchange.key=** must equals to properties **eggroll.rollsite.route.table.key=**
> > > 
> > > 
> > > I know, but this part of the description does not say that it is necessary to add the route information with the party id as exchange. https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_eggroll/fate-exchange_deployment_guide.zh.md#543-eggroll%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BF%AE%E6%94%B9
> > > So, I just need to add an exchange, ok?
> > 
> > 
> > Yes
> 
> thanks!
> 
> In addition, I would like to ask a question, whether the exchange gateway entry in this picture, as well as the ip and port of the rollsite entry and exit are all configured correctly, as well as the routing information below. ![image](https://user-images.githubusercontent.com/35909818/154010077-d88f50e6-8262-44eb-b296-fac4532e3dd9.png)

You should make sure those ip is match with your machine.

**Comment by amenhub** [comment]
ok, thanks @pizhicheng
