### ISSUE TITLE
./fate_manager 运行报错

### ISSUE THREAD

**Issue by hushh1995** [FederatedAI/FATE-Cloud#21]
[2021-01-25 21:09:59] [info] replacing callback `gorm:update_time_stamp` from D:/webank/Federated/FATE-Cloud/fate-manager/src/models/models.go:53

[2021-01-25 21:09:59] [info] replacing callback `gorm:update_time_stamp` from D:/webank/Federated/FATE-Cloud/fate-manager/src/models/models.go:54

[2021-01-25 21:09:59] [info] replacing callback `gorm:delete` from D:/webank/Federated/FATE-Cloud/fate-manager/src/models/models.go:55
/data/logs/fate-cloud/fate-manager/2021-01-25/ fate-manager.debug.log
/data/logs/fate-cloud/fate-manager/2021-01-25/ fate-manager.info.log
/data/logs/fate-cloud/fate-manager/2021-01-25/ fate-manager.warn.log
/data/logs/fate-cloud/fate-manager/2021-01-25/ fate-manager.error.log
/data/logs/fate-cloud/fate-manager/2021-01-25/ fate-manager.fatal.log

(D:/webank/Federated/FATE-Cloud/fate-manager/src/models/accountInfo.go:77)
[2021-01-25 21:09:59]  [0.93ms]  SELECT * FROM `t_fate_account_info`  WHERE (status = 1) AND (role = 1) AND (cloud_user_id is not null)
[0 rows affected or returned ]
panic: open ./fate-manager/static/*/*: no such file or directory

goroutine 1 [running]:
html/template.Must(...)
	D:/Go/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLFiles(0xb4f4840, 0xbb0eed0, 0x1, 0x1)
	D:/webankGo/pkg/mod/github.com/gin-gonic/gin@v1.6.2/gin.go:204 +0x281
fate.manager/routers.InitRouter(0x0)
	D:/webank/Federated/FATE-Cloud/fate-manager/src/routers/router.go:133 +0x1da0
main.main()
	D:/webank/Federated/FATE-Cloud/fate-manager/src/fate_manager.go:48 +0x71

**Comment by hushh1995** [comment]
这个错误信息是什么意思啊
